# Basic Settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

# Rebind prefix key
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Refind split windows 
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind b split-window -v -c "#{pane_current_path}"

# Vim bind navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Move windows with Shift-X
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n S-Left previous-window
bind -n S-Right next-window

# Window List 
bind s choose-session

# Reload config
unbind r 
bind r source-file $HOME/.config/tmux/tmux.conf

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# QoL
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g detach-on-destroy off

set -g allow-passthrough on

# Continuum and Resurrect
set -g @continuum-restore 'on'
run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.config/tmux/plugins/tmux-continuum/continuum.tmux
